version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "codebreakercontest6"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kydcdcfv2zes"
s3_prefix = "codebreakercontest6"
region = "ap-southeast-1"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "JudgeName=\"codebreakercontest6\""
image_repositories = []
