version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "codebreakercontest01"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kydcdcfv2zes"
s3_prefix = "codebreakercontest01"
region = "ap-southeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "JudgeName=\"codebreakercontest01\""
image_repositories = []
